// ===================================================================
// GENERATED BY task42_full.py -- DO NOT EDIT BY HAND
// Re-run  python3 task42_full.py  to change any of this.
// ===================================================================
// image      : pic014.jpg
// generated  : 2026-08-17 15:56:51
// start      : (7, 2) facing EAST
// goal       : (8, 5)
//
// The waypoints for the middle stage are in gen_task42.h, written by
// the same run of this script.
#pragma once

#define GEN_TASK42FULL_IMAGE "pic014.jpg"

#define PRE_OBSTACLE_PATH   "llfrffflfrfrff"
#define POST_OBSTACLE_PATH  "frflfrffffrflfrflfrf"
#define MAZE_START_ROW      7
#define MAZE_START_COL      2
#define MAZE_START_DIR      mtrn3100::Maze::EAST
