// ===================================================================
// GENERATED BY obstacle_solver.py -- DO NOT EDIT BY HAND
// Re-run  python3 obstacle_solver.py  to change any of this.
// ===================================================================
// image        : pic014.jpg
// generated    : 2026-08-17 15:56:51
// section      : rows 0-4, cols 2-6
// robot        : 95 x 76 mm
// clearance    : 15.0 mm at the tightest point
//
// Waypoints are in GLOBAL maze millimetres.
// x = east (column), y = south (row); cell centre = (index + 0.5) * 180
#pragma once

#define GEN_TASK42_IMAGE "pic014.jpg"

const mtrn3100::Waypoint OBSTACLE_WAYPOINTS[] = {
    {    450.0f,    630.0f },   // entry cell
    {    502.5f,    582.5f },
    {    782.5f,    582.5f },
    {   1012.5f,    352.5f },
    {   1072.5f,    352.5f },
    {   1107.5f,    337.5f },
    {   1170.0f,    270.0f },   // exit cell
};
#define OBSTACLE_WAYPOINT_COUNT  7

#define OBS_ENTRY_ROW   3    // robot starts here for TASK_NUM 2
#define OBS_ENTRY_COL   2
#define OBS_ENTRY_DIR   mtrn3100::Maze::EAST    // facing this way
#define OBS_EXIT_ROW    1
#define OBS_EXIT_COL    6
#define OBS_EXIT_DIR    mtrn3100::Maze::EAST
