// ===================================================================
// GENERATED BY maze_solver.py -- DO NOT EDIT BY HAND
// Re-run  python3 maze_solver.py  to change any of this.
// ===================================================================
// image      : pic007.jpg
// generated  : 2026-08-17 15:27:32
// start      : (0, 4) facing EAST
// goal       : (8, 6)
// path       : 26 characters
#pragma once

#define GEN_TASK41_IMAGE "pic007.jpg"

#define PATH      "flflfrflffrfrrflffrflfrfrf"
#define START_ROW 0
#define START_COL 4
#define START_DIR mtrn3100::Maze::EAST
#define GOAL_ROW  8
#define GOAL_COL  6
