/**
 * Week 12 Assessment
 *
 *  ==================================================================
 *   THE ONLY LINE YOU EDIT IN THIS FILE IS  TASK_NUM,  DIRECTLY BELOW
 *  ==================================================================
 *
 *  Everything else -- paths, waypoints, start cells, headings -- is written
 *  by the Python scripts into gen_task41.h / gen_task42.h / gen_task42_full.h
 *  and included further down. There is nothing to copy and paste, so the
 *  numbers cannot end up coming from two different photos.
 *
 *   TASK_NUM   what it does                          run this first
 *   --------   ----------------------------------    ---------------------
 *      1       4.1 maze race                         python3 maze_solver.py
 *      2       4.2 obstacle section only  (2 marks)  python3 obstacle_solver.py
 *      3       4.3 autonomous mapping     NOT DONE   -- see note below
 *      4       4.2 full maze through it   (4 marks)  python3 task42_full.py
 *
 *  Then always:  python3 preflight.py     before uploading.
 *
 *  NOTE ON TASK_NUM 3: MazeNavigator::exploreAndSolveMaze() is an empty stub.
 *  The robot will sit still. Do not use it expecting a result.
 *
 */

#define TASK_NUM 2


// =====================================================================
//  Below here is wiring and tuning. You should not need to touch any of
//  it on assessment day.
// =====================================================================

#include <Wire.h>
#include <MPU6050_light.h>

#include "Motor.hpp"
#include "DualEncoder.hpp"
#include "PIDController.hpp"
#include "Lidars.hpp"
#include "Pose.hpp"
#include "MotionController.hpp"
#include "Maze.hpp"
#include "MazeNavigator.hpp"
#include "ObstacleNavigator.hpp"

// ---------------------------------------------------------------------
//  Generated by the Python solvers. DO NOT EDIT THESE FILES BY HAND --
//  re-run the script instead and they update themselves.
//
//    gen_task41.h        <- maze_solver.py       (task 1)
//    gen_task42.h        <- obstacle_solver.py   (tasks 2 and 4)
//    gen_task42_full.h   <- task42_full.py       (task 4)
// ---------------------------------------------------------------------
#include "gen_task41.h"
#include "gen_task42.h"
#include "gen_task42_full.h"

#define USE_LIDAR_CORRECTION 1 // 0: odometry only, 1: with snapToWall correction

// Motor pins (DRV8835, Phase/Enable mode)
#define MOT1_PWM  9
#define MOT1_DIR  10
#define MOT2_PWM  11
#define MOT2_DIR  12

// Encoder pins
#define ENC1_A  2
#define ENC1_B  4
#define ENC2_A  3
#define ENC2_B  5

// LiDAR enable pins
#define LIDAR_FRONT_EN  A2
#define LIDAR_RIGHT_EN  A1
#define LIDAR_LEFT_EN   A0

// PID gains
#define HEADING_KP  130.0f
#define HEADING_KI  0.0f
#define HEADING_KD  0.1f
#define DISTANCE_KP 14.0f
#define DISTANCE_KI 0.0f
#define DISTANCE_KD 0.1f

// Tuned Parameters
#define WALL_THRESHOLD 100
#define CELL_M 0.18f
const uint16_t CPR = 690;

// Hardware
mtrn3100::Motor motorL(MOT1_PWM, MOT1_DIR);
mtrn3100::Motor motorR(MOT2_PWM, MOT2_DIR);
mtrn3100::DualEncoder encoder(ENC1_A, ENC1_B, ENC2_A, ENC2_B);
MPU6050 mpu(Wire);
mtrn3100::Lidars lidars(LIDAR_FRONT_EN, LIDAR_RIGHT_EN, LIDAR_LEFT_EN, WALL_THRESHOLD);

// PID Controllers
mtrn3100::PIDController headingPid(HEADING_KP, HEADING_KI, HEADING_KD);
mtrn3100::PIDController distancePid(DISTANCE_KP, DISTANCE_KI, DISTANCE_KD);

mtrn3100::Pose pose(mpu);
mtrn3100::MotionController motion(pose, lidars, mpu, motorL, motorR, encoder, headingPid, distancePid);
mtrn3100::Maze maze(GOAL_ROW, GOAL_COL);
mtrn3100::MazeNavigator mazeNav(maze, motion);
mtrn3100::ObstacleNavigator obstacleNav(pose, motion);

// Heading in radians for a maze direction (NORTH = 0, EAST = +PI/2, ...)
float headingOf(mtrn3100::Maze::Direction dir) {
    switch (dir) {
        case mtrn3100::Maze::NORTH: return 0.0f;
        case mtrn3100::Maze::EAST:  return M_PI / 2.0f;
        case mtrn3100::Maze::SOUTH: return M_PI;
        default:                    return -M_PI / 2.0f;  // WEST
    }
}

void initHardware() {
    Wire.begin();
    lidars.begin();

    byte status = mpu.begin();
    if (status != 0) {
        Serial.print(F("IMU failed (")); Serial.print(status); Serial.println(F(")."));
        while (1);
    }

    // force ±500 deg/s gyro range (battery-mode bug fix)
    Wire.beginTransmission(0x68);
    Wire.write(0x1B);
    Wire.write(0x08);
    Wire.endTransmission();

    Serial.println(F("Calibrating IMU, hold still..."));
    delay(1000);
    mpu.calcOffsets(true, true);
    Serial.println(F("IMU ready."));

    float x = (START_COL + 0.5f) * CELL_M;
    float y = (START_ROW + 0.5f) * CELL_M;
    pose.reset(x, y, headingOf(START_DIR));

    motion.stop();
}

void setup() {
    Serial.begin(115200);
    initHardware();

    motion.setLidarCorrection(USE_LIDAR_CORRECTION);

    // Say out loud which task is about to run and where the robot must be
    // placed, so a wrong TASK_NUM or a misplaced robot is obvious before it
    // starts moving rather than after.
    Serial.println();
    Serial.println(F("======================================"));
    #if   TASK_NUM == 1
        Serial.println(F("TASK 1  - 4.1 maze race"));
        Serial.print(F("  place robot at cell ("));
        Serial.print(START_ROW); Serial.print(F(", ")); Serial.print(START_COL);
        Serial.println(F(")"));
        Serial.print(F("  image used: ")); Serial.println(F(GEN_TASK41_IMAGE));
    #elif TASK_NUM == 2
        Serial.println(F("TASK 2  - 4.2 obstacle section only"));
        Serial.print(F("  place robot at cell ("));
        Serial.print(OBS_ENTRY_ROW); Serial.print(F(", ")); Serial.print(OBS_ENTRY_COL);
        Serial.println(F(")"));
        Serial.print(F("  image used: ")); Serial.println(F(GEN_TASK42_IMAGE));
    #elif TASK_NUM == 3
        Serial.println(F("TASK 3  - 4.3 NOT IMPLEMENTED, robot will not move"));
    #elif TASK_NUM == 4
        Serial.println(F("TASK 4  - 4.2 full maze"));
        Serial.print(F("  place robot at cell ("));
        Serial.print(MAZE_START_ROW); Serial.print(F(", ")); Serial.print(MAZE_START_COL);
        Serial.println(F(")"));
        Serial.print(F("  image used: ")); Serial.println(F(GEN_TASK42FULL_IMAGE));
    #endif
    Serial.println(F("======================================"));
}

void loop() {

    // initial delay for 5s
    delay(2000);
    Serial.println(F("Task starting in 3 seconds"));
    delay(3000);

    #if TASK_NUM == 1
        mazeNav.executePath(PATH, START_ROW, START_COL, START_DIR);

    #elif (TASK_NUM == 2)
        // Standalone continuous-section run (2 marks). The robot is placed by
        // hand in the entry cell, facing the way it would have entered.
        //
        // The section has no walls, so snapToWall() is disabled — it would
        // latch onto a cylinder and corrupt the pose. ObstacleNavigator turns
        // the front LiDAR into a plain collision guard instead.
        pose.reset((OBS_ENTRY_COL + 0.5f) * CELL_M,
                   (OBS_ENTRY_ROW + 0.5f) * CELL_M,
                   headingOf(OBS_ENTRY_DIR));

        if (obstacleNav.executeWaypoints(OBSTACLE_WAYPOINTS,
                                         OBSTACLE_WAYPOINT_COUNT,
                                         headingOf(OBS_EXIT_DIR))) {
            // Clear of the cylinders and squared up: drive out of the section.
            motion.setLidarCorrection(true);
            motion.forwardOneCell();
        }

    #elif (TASK_NUM == 3)
        Serial.println(F("4.3 is not implemented - nothing to run."));

    #elif (TASK_NUM == 4)
        // Full maze run through the obstacle course (Task 4.2, all 5 marks).
        // Three stages: walled maze -> continuous section -> walled maze.
        pose.reset((MAZE_START_COL + 0.5f) * CELL_M,
                   (MAZE_START_ROW + 0.5f) * CELL_M,
                   headingOf(MAZE_START_DIR));

        // Stage 1 — grid navigation up to the entry cell, walls available.
        motion.setLidarCorrection(true);
        if (mazeNav.executePath(PRE_OBSTACLE_PATH, MAZE_START_ROW,
                                MAZE_START_COL, MAZE_START_DIR)) {

            // Stage 2 — continuous section. executeWaypoints turns LiDAR
            // snapping off itself and re-enables the collision guard.
            if (obstacleNav.executeWaypoints(OBSTACLE_WAYPOINTS,
                                             OBSTACLE_WAYPOINT_COUNT,
                                             headingOf(OBS_EXIT_DIR))) {

                // Stage 3 — back on the grid. The first forwardOneCell of this
                // path drives out through the opening and snaps against a wall,
                // recovering whatever drift the section introduced.
                motion.setLidarCorrection(true);
                mazeNav.executePath(POST_OBSTACLE_PATH, OBS_EXIT_ROW,
                                    OBS_EXIT_COL, OBS_EXIT_DIR);
            }
        }

    #endif

    Serial.println(F("Done. Switch off."));
    while (true) { delay(1000); }   // halt — prevent loop() restarting the path
}
